// Auto-generated by ml/src/export.py — do not edit by hand.
//
// Placeholder. `vibrosense_model_tflite_len == 0` signals to `Inference::begin()`
// that no real model has been trained yet; the firmware will compile, flash,
// advertise BLE, and accept CAPTURE-mode raw_window streaming, but inference
// will short-circuit to `HEALTHY @ 0.0`. Run `make ml-pipeline` (or, after
// real captures: `make train && make quantize && make export`) to overwrite
// this file with a real INT8 model — see PROJECT_PLAN.md §10.
#pragma once

alignas(8) const unsigned char vibrosense_model_tflite[1] = { 0x00 };
const unsigned int vibrosense_model_tflite_len = 0;
