"""TFLite → C header at firmware/nano33/model/model.h.

Usage:
    python -m ml.src.export ml/artifacts/cnn.tflite
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER_TEMPLATE = """// Auto-generated by ml/src/export.py — do not edit by hand.
#pragma once

alignas(8) const unsigned char vibrosense_model_tflite[] = {{
{body}
}};
const unsigned int vibrosense_model_tflite_len = {n};
"""


def _format_bytes(data: bytes, per_line: int = 12) -> str:
    return ",\n".join(
        "  " + ", ".join(f"0x{b:02x}" for b in data[i : i + per_line])
        for i in range(0, len(data), per_line)
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("tflite")
    p.add_argument("--out", default="firmware/nano33/model/model.h")
    args = p.parse_args()

    data = Path(args.tflite).read_bytes()
    text = HEADER_TEMPLATE.format(body=_format_bytes(data), n=len(data))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
